use tauri_specta::{collect_commands, Builder};

pub fn generate_bindings() -> Builder<tauri::Wry> {
    use crate::features::{
        cloud_session_commands, example_feature_commands, notifications_commands,
        preferences_commands, quick_pane_commands, recovery_commands,
    };

    Builder::<tauri::Wry>::new().commands(collect_commands![
        // Preferences feature
        preferences_commands::greet,
        preferences_commands::load_preferences,
        preferences_commands::save_preferences,
        // Notifications feature
        notifications_commands::send_native_notification,
        // Recovery feature
        recovery_commands::save_emergency_data,
        recovery_commands::load_emergency_data,
        recovery_commands::cleanup_old_recovery_files,
        // Quick pane feature
        quick_pane_commands::show_quick_pane,
        quick_pane_commands::dismiss_quick_pane,
        quick_pane_commands::toggle_quick_pane,
        quick_pane_commands::get_default_quick_pane_shortcut,
        quick_pane_commands::update_quick_pane_shortcut,
        // Example feature (template)
        example_feature_commands::load_example_data,
        example_feature_commands::save_example_data,
        // Cloud session feature
        cloud_session_commands::load_cloud_config,
        cloud_session_commands::save_cloud_config,
        cloud_session_commands::clear_cloud_config,
        cloud_session_commands::vault_get,
        cloud_session_commands::vault_set,
        cloud_session_commands::vault_clear,
    ])
}

/// Export TypeScript bindings to the frontend.
///
/// Invoked automatically in debug builds (see `run()`), and manually via
/// `npm run rust:bindings` (the `gen_bindings` binary). Do NOT regenerate with
/// `cargo test export_bindings` — that fails on Windows (see the test below).
pub fn export_ts_bindings() {
    generate_bindings()
        .export(
            specta_typescript::Typescript::default()
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n"),
            "../src/lib/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generate TypeScript bindings file (non-Windows / ad-hoc fallback).
    ///
    /// Prefer `npm run rust:bindings` (the `gen_bindings` binary). On Windows
    /// this test path fails with STATUS_ENTRYPOINT_NOT_FOUND (0xc0000139)
    /// because the test harness runs from `target/debug/deps/` without the
    /// staged WebView2 DLL. Ignored by default so it never runs in CI.
    #[test]
    #[ignore]
    fn export_bindings() {
        export_ts_bindings();
        println!("✓ TypeScript bindings exported to ../src/lib/bindings.ts");
    }
}
